//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_finance
    {
        public int f_id { get; set; }
        public string f_floor { get; set; }
        public string f_user { get; set; }
        public double f_transaction { get; set; }
        public string f_desc { get; set; }
        public string f_transactiontype { get; set; }
        public string f_paymentmethod { get; set; }
        public System.DateTime f_date { get; set; }
        public string f_receipt { get; set; }
    
        public virtual tb_user tb_user { get; set; }
        public virtual tb_floor tb_floor { get; set; }
    }
}
