//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_floor()
        {
            this.tb_inventory = new HashSet<tb_inventory>();
            this.tb_room = new HashSet<tb_room>();
        }
    
        public string fl_id { get; set; }
        public string fl_bid { get; set; }
        public string fl_wifipwd { get; set; }
        public string fl_modemip { get; set; }
        public byte[] fl_cctvqr { get; set; }
        public byte[] fl_layout { get; set; }
        public int fl_landlord { get; set; }
    
        public virtual tb_landlord tb_landlord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_inventory> tb_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_room> tb_room { get; set; }
    }
}
