//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_investor
    {
        public int i_id { get; set; }
        public string i_user { get; set; }
        public int i_lot { get; set; }
        public double i_lotpercentage { get; set; }
    }
}
