//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inventory
    {
        public int iv_id { get; set; }
        public int iv_floor { get; set; }
        public string iv_item { get; set; }
        public int iv_count { get; set; }
        public string iv_active { get; set; }
    
        public virtual tb_floor tb_floor { get; set; }
    }
}
