//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_landlord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_landlord()
        {
            this.tb_floor = new HashSet<tb_floor>();
        }
    
        public int l_id { get; set; }
        public string l_name { get; set; }
        public string l_phone { get; set; }
        public double l_fee { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = false)]
        public System.DateTime l_due { get; set; }
        public string l_bank { get; set; }
        public string l_active { get; set; }
        public int l_bankname { get; set; }
    
        public virtual tb_bankname tb_bankname { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_floor> tb_floor { get; set; }
    }
}
