//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tb_profit
    {
        public int p_id { get; set; }
        public int p_investor { get; set; }
        public string p_month { get; set; }
        public double p_profit { get; set; }

        public virtual tb_investor tb_investor { get; set; }

        public string InvestorUsername { get; set; }

        public int p_lot { get; set; }
    }
}