//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_room
    {
        public string r_id { get; set; }
        public string r_floor { get; set; }
        public double r_price { get; set; }
        public int r_availability { get; set; }
        public Nullable<int> r_tenant { get; set; }
        public double r_size { get; set; }
    
        public virtual tb_floor tb_floor { get; set; }
        public virtual tb_tenant tb_tenant { get; set; }
    }
}
