//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tenant()
        {
            this.tb_room = new HashSet<tb_room>();
        }
    
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string t_ic { get; set; }
        public string t_uploadic { get; set; }
        public string t_contract { get; set; }
        public string t_phone { get; set; }
        public string t_emergency { get; set; }
        public System.DateTime t_indate { get; set; }
        public System.DateTime t_outdate { get; set; }
        public int t_siri { get; set; }
        public double t_outstanding { get; set; }
        public int t_paymentstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_room> tb_room { get; set; }
    }
}
