//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public string u_username { get; set; }
        public string u_pwd { get; set; }
        public string u_email { get; set; }
        public int u_usertype { get; set; }
    }
}
